### ISSUE TITLE
Save data to json file fails when data contains numpy.int64 type in Python=3.7

### ISSUE THREAD

**Issue by rodriguez-facundo** [Neurosim-lab/netpyne#403]
## Error
It seems numpy types can't be dump in json files. 

## ErrorLog:

```
snakes$ python init.py 
Note: pyNeuroML version 0.3.11 is installed but at least v0.3.13 is required

Creating network of 4 cell populations on 1 hosts...
  Number of cells on node 0: 484 
  Done; cell creation time = 1.51 s.
Making connections...
  Number of connections on node 0: 160567 
  Number of synaptic contacts on node 0: 306493 
  Done; cell connection time = 22.31 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 0 traces of 0 types on node 0

Gathering data...
  Done; gather time = 8.57 s.

Analyzing...
  Cells: 484
  Connections: 160567 (331.75 per cell)
  Synaptic contacts: 306493 (633.25 per cell)
Saving output as data/default.json  ... 
Traceback (most recent call last):
  File "init.py", line 15, in <module>
    sim.saveData()
  File "/Users/snakes/Desktop/NetPyNE-UI/netpyne/netpyne/sim/save.py", line 140, in saveData
    sim.saveJSON(filePath+'.json', dataSave)
  File "/Users/snakes/Desktop/NetPyNE-UI/netpyne/netpyne/sim/save.py", line 39, in saveJSON
    separators=(',', ': '), ensure_ascii=True)
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/snakes/miniconda3/envs/snakes/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```

## Steps to reproduce:

-  create venv with python3.7, and install netpyne@development
- `git clone -b netpyne https://github.com/jonescompneurolab/hnn.git`
- `cd hnn && python init.py`

**Comment by rodriguez-facundo** [comment]
Hi 👋 @salvadord, good for Ariel to give it a try?
--- 

Still an issue:

Hints: 
- Code fails at https://github.com/Neurosim-lab/netpyne/blob/688ea2bd3a1b57ea415d4a505934f114af4b3666/netpyne/sim/save.py#L37
- Use a custom JSON serializer to change the types from `numpy int` to `python int`. 

```python
class MyCoolCustomSerializer(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyCoolCustomSerializer, self).default(obj)

# netpyne/sim/save.py#L37
json.dumps(data, cls=NpEncoder)
str_ = json.dumps(data,
    indent=4,
    sort_keys=True,
    separators=(',', ': '), 
    ensure_ascii=False,
    cls=MyCoolCustomSerializer)
```

**Comment by salvadord** [comment]
Sure! thanks
