### ISSUE TITLE
'pip install netpyne' causing matplotlib backend error on mac os x

### ISSUE THREAD

**Issue by ericaygriffith** [Neurosim-lab/netpyne#496]
**Describe the Bug** 
Netpyne installation using 'pip install netpyne' on Mac OS 10.15.4 (Catalina) leads to a matplotlib backend error that prevents "sim" from being properly imported from netpyne (can still do 'from netpyne import specs' -- error is restricted to 'from netpyne import sim'). Additionally, after netpyne install from pip install netpyne, 'import matplotlib.pyplot as plot' results in a new but similar error -- however 'import matplotlib' still works. 

     RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to 
     function correctly if Python is not installed as a framework. See the Python documentation for 
     more information on installing Python as a framework on Mac OS X. Please either reinstall 
     Python as a framework, or try one of the other backends. If you are using (Ana)Conda please 
     install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib 
     on OSX' in the Matplotlib FAQ for more information.

**Reproducing the bug**

1. On a mac (with no version of anaconda, neuron, or netpyne installed), install anaconda (graphical installer for python 3.7). Install neuron 7.7 from neuron.yale.edu. Verify both are working. [*At this point, should still be able to do: from matplotlib import pyplot as plt]

2. Install netpyne from command line using 'pip install netpyne' (*output attached* -- appears that versions of matplotlib and pandas are uninstalled)
```
>>> pip install netpyne
Collecting netpyne
  Using cached netpyne-0.9.6-py2.py3-none-any.whl (262 kB)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.7/site-packages (from netpyne) (1.18.1)
Requirement already satisfied: scipy in ./opt/anaconda3/lib/python3.7/site-packages (from netpyne) (1.4.1)
Collecting matplotlib-scalebar
  Using cached matplotlib_scalebar-0.6.2-py2.py3-none-any.whl (15 kB)
Collecting matplotlib<=2.2.4,>2.2
  Using cached matplotlib-2.2.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.0 MB)
Requirement already satisfied: future in ./opt/anaconda3/lib/python3.7/site-packages (from netpyne) (0.18.2)
Collecting pandas==0.23.4
  Using cached pandas-0.23.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.4 MB)
Requirement already satisfied: python-dateutil>=2.1 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib<=2.2.4,>2.2->netpyne) (2.8.1)
Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib<=2.2.4,>2.2->netpyne) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib<=2.2.4,>2.2->netpyne) (1.1.0)
Requirement already satisfied: pytz in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib<=2.2.4,>2.2->netpyne) (2019.3)
Requirement already satisfied: six>=1.10 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib<=2.2.4,>2.2->netpyne) (1.14.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib<=2.2.4,>2.2->netpyne) (2.4.6)
Requirement already satisfied: setuptools in ./opt/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib<=2.2.4,>2.2->netpyne) (46.0.0.post20200309)
Installing collected packages: matplotlib, matplotlib-scalebar, pandas, netpyne
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.1.3
    Uninstalling matplotlib-3.1.3:
      Successfully uninstalled matplotlib-3.1.3
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.1
    Uninstalling pandas-1.0.1:
      Successfully uninstalled pandas-1.0.1
Successfully installed matplotlib-2.2.4 matplotlib-scalebar-0.6.2 netpyne-0.9.6 pandas-0.23.4
```

3. At this point, "from netpyne import sim" does not work:
```
>>> from netpyne import sim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/netpyne/sim/__init__.py", line 72, in <module>
    from .. import analysis
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/netpyne/analysis/__init__.py", line 26, in <module>
    from .utils import exception, _showFigure, _saveFigData, getCellsInclude, getCellsIncludeTags, _roundFigures, \
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/netpyne/analysis/utils.py", line 31, in <module>
    import matplotlib.pyplot as plt
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to
function correctly if Python is not installed as a framework. See the Python documentation for
more information on installing Python as a framework on Mac OS X. Please either reinstall Python
as a framework, or try one of the other backends. If you are using (Ana)Conda please install
python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in
the Matplotlib FAQ for more information.
```

4. "from matplotlib import pyplot as plt" also does not work now. See error below. (Uninstalling and then re-installing anaconda worked to solve the error, but error re-appears after pip install netpyne.)

```
>>> from matplotlib import pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "/Users/daviddonofrio/opt/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to
function correctly if Python is not installed as a framework. See the Python documentation for
more information on installing Python as a framework on Mac OS X. Please either reinstall Python
as a framework, or try one of the other backends. If you are using (Ana)Conda please install
python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in
the Matplotlib FAQ for more information.
```

**Expected Behavior**
I expect to be able to import specs and sim from netpyne after installing with pip install netpyne, as well as matplotlib.pyplot. 

**System information**
- Mac OS X 10.15.4 (Catalina)
- NEURON version:  VERSION 7.7.2 7.7 (2b7985ba) 2019-06-20
 - NetPyNE version: 0.9.6
 - Python version: 3.7.6

**Additional context**
Other users have run into this error. One other user (mac os x mojave, python 3.7, neuron 7.7) had these same errors when installing then using netpyne in both spyder and from the command line, but after uninstalling and reinstalling a broken neuron installation, they were able to run these commands without an issue, but only in their terminal (spyder still generates the same errors).

**Comment by ericaygriffith** [comment]
**Solution**

Change the default backend being used by matplotlib from macosx to TkAgg.  

\
**Steps**  

1. **Test if this solution will work**: 
```
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
```
If no errors result, then matplotlib can use TkAgg backend. 

\
2. **Find matplotlibrc startup script**:
```
import matplotlib
print(matplotlib.matplotlib_fname())
```
This will show the path to the matplotlibrc file, probably something similar to:
```
path/to/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/matplotlibrc
```

\
3. **Edit this matplotlibrc file**. Change the line
```
backend      : macosx
```
to 
```
backend      : TkAgg
```

\
4. **Test change in python**:
```
import matplotlib.pyplot as plt
```
should no longer give any errors. 
And
```
from netpyne import sim
```
should work as well.

**Comment by ericaygriffith** [comment]
Seems the issue may be that netpyne is only compatible with matplotlib up to version 2.2.4. Anaconda install (using graphical installer for python 3.7 for mac os x) now by default installs matplotlib v3.x. It appears (see output of 'pip install netpyne' above) that netpyne may uninstall the newer version of matplotlib and re-install the older 2.2.4 version, potentially in a way that makes it difficult to access in anaconda. So, if anaconda was installed on your system before this matplotlib upgrade, you may not run into this issue, but if you have installed it recently, the fix describe above (or something similar) should hopefully provide a reasonable bandaid.
