### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by MP1233** [Neurosim-lab/netpyne#625]
http://www.netpyne.org/tutorial.html#tutorial-1-quick-and-easy-example

ubuntu@ubuntu-G3-3579:/media/ubuntu/OS/braingame$ python tut1.py
Traceback (most recent call last):
  File "tut1.py", line 1, in <module>
    import HHTut
  File "/media/ubuntu/OS/braingame/HHTut.py", line 5, in <module>
    from netpyne import specs, sim
  File "/home/ubuntu/.local/lib/python2.7/site-packages/netpyne/__init__.py", line 21, in <module>
    from netpyne import analysis
  File "/home/ubuntu/.local/lib/python2.7/site-packages/netpyne/analysis/__init__.py", line 63, in <module>
    from .rxd import plotRxDConcentration
  File "/home/ubuntu/.local/lib/python2.7/site-packages/netpyne/analysis/rxd.py", line 22, in <module>
    from matplotlib_scalebar.scalebar import ScaleBar
  File "/home/ubuntu/.local/lib/python2.7/site-packages/matplotlib_scalebar/scalebar.py", line 526
    f"Unknown dimension: {dimension}. "
                                      ^
SyntaxError: invalid syntax

**Comment by joewgraham** [comment]
Hi @MP1233 , thank you for the bug report.  

It looks like the error is coming from a different Python package (matplotlib_scalebar).  It also looks like you're trying to run the tutorial in Python 2, which many packages no longer support.  I would recommend upgrading to Python 3.  

Please let us know if you have any more issues.
